require:
  - rubocop-rails

AllCops:
 NewCops: enable
 SuggestExtensions: false
 TargetRubyVersion: 2.7.2
 Exclude:
   - 'app/controllers/candidates/*'
   - 'app/controllers/recruiters/*'
   - 'bin/**/*'
   - 'vendor/**/*'
   - 'db/migrate/*'
   - 'db/schema.rb'
   - 'config/**/*'
   - 'script/**/*'
   - 'spec/rails_helper.rb'
   - 'node_modules/node-sass/src/libsass/**/*'

Style/Documentation:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/AsciiComments:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Metrics/BlockLength:
  IgnoredMethods: ['describe', 'context', 'feature', 'scenario', 'let']

Layout/LineLength:
  Max: 80
