PERSONAL_DOMAINS = ['007addict.com', '020.co.uk', '123.com', '123box.net', '123india.com',
     '123qwe.co.uk', '138mail.com', '150mail.com', '150ml.com', '15meg4free.com',
     '16mail.com', '1auto.com', '1colony.com', '1freeemail.com', '247emails.com',
     '24horas.com', '2coolforyou.net', '2die4.com', '2hotforyou.net', '2mydns.com', 
     '2net.us', '360.ru', '37.com', '3ammagazine.com', '3email.com', '3xl.net', '444.net', 
     '4email.com', '4mg.com', '4newyork.com', '4x4fan.com', '50mail.com', '5fm.za.com', 
     '5iron.com', '702mail.co.za', '8848.net', 'a-player.org', 'a2z4u.net', 'aahlife.com', 
     'aaronkwok.net', 'abbeyroadlondon.co.uk', 'aberystwyth.com', 'about.com', 'absolutevitality.com', 
     'abv.bg', 'acceso.or.cr', 'access4less.net', 'accessgcc.com', 'accountant.com', 'acdczone.com', 
     'acmemail.net', 'acninc.net', 'acrobatmail.com', 'adexec.com', 'adres.nl', 'aeiou.pt', 
     'aemail4u.com', 'aeneasmail.com', 'afreeinternet.com', 'africa-11.com', 'africamail.com', 
     'africanpartnersonline.com', 'agelessemail.com', 'agoodmail.com', 'ahaa.dk', 'aichi.com', 
     'aiutamici.com', 'aknet.kg', 'akphantom.com', 'albawaba.com', 'alex4all.com', 'alexandria.cc', 
     'algeria.com', 'algeriamail.com', 'aliceinchainsmail.com', 'allergist.com', 'alloymail.com', 
     'allsaintsfan.com', 'alskens.dk', 'altavista.com', 'altavista.se', 'alternativagratis.com', 
     'alumnidirector.com', 'amele.com', 'america.hm', 'amrer.net', 'amuro.net', 'amuromail.com', 
     'ananzi.co.za', 'andreabocellimail.com', 'andylau.net', 'anfmail.com', 'angelfire.com', 'anjungcafe.com', 
     'anniefans.com', 'anti-ignorance.net', 'antiqueemail.com', 'antwerpen.com', 'anymoment.com', 
     'anytimenow.com', 'aon.at', 'apexmail.com', 'apollo.lv', 'aport.ru', 'aport2000.ru', 'apple.sib.ru', 
     'approvers.net', 'aquaticmail.net', 'arabia.com', 'arabtop.net', 'archaeologist.com', 'archerymail.com', 
     'arcor.de', 'arcticmail.com', 'argentina.com', 'arhaelogist.com', 'arnet.com.ar', 'artistemail.com', 
     'artlover.com', 'artlover.com.au', 'asean-mail.com', 'asheville.com', 'asia-links.com', 'asia.com', 
     'asianavenue.com', 'asiancityweb.com', 'asianwired.net', 'askaclub.ru', 'assamesemail.com', 
     'astroboymail.com', 'asurfer.com', 'atlas.cz', 'atlaswebmail.com', 'atozasia.com', 'atrus.ru', 'au.ru', 
     'aufeminin.com', 'aus-city.com', 'ausi.com', 'australiamail.com', 'automail.ru', 'avh.hu', 'avtoritet.ru', 
     'awayonvacation.com', 'ayna.com', 'backfliper.com', 'backstreetboysclub.com', 'backtothefuturefans.com', 
     'badtzmail.com', 'bakpaka.com', 'bakpaka.net', 'ballerstatus.net', 'balochistan.org', 'baluch.com', 
     'baptistmail.com', 'baptized.com', 'barlick.net', 'baseball-email.com', 'batuta.net', 'bboy.com', 
     'bcvibes.com', 'beep.ru', 'beer.com', 'beerandremotes.com', 'beethoven.com', 'beirut.com', 'belizehome.com', 
     'belizemail.net', 'belizeweb.com', 'berlin.com', 'berlin.de', 'bharatmail.com', 'big5mail.com', 
     'bigfoot.com', 'bigfoot.de', 'bigger.com', 'bigmailbox.com', 'bigramp.com', 'bikerider.com', 'biologyfan.com', 
     'birdfanatic.com', 'bizhosting.com', 'bk.ru', 'bkkmail.com', 'blackburnfans.com', 'blackburnmail.com', 
     'blackplanet.com', 'blazemail.com', 'blink182.net', 'blondandeasy.com', 'bluebottle.com', 'bluemail.ch', 
     'bluemail.dk', 'blushmail.com', 'bmlsports.net', 'boardermail.com', 'boarderzone.com', 'bol.com.br', 
     'bolando.com', 'bollywoodz.com', 'bolt.com', 'bonbon.net', 'boom.com', 'bootmail.com', 'bornagain.com', 
     'bostonoffice.com', 'bounce.net', 'boxemail.com', 'boyzoneclub.com', 'brasilia.net', 'bratan.ru', 
     'brazilmail.com.br', 'breathe.com', 'brestonline.com', 'brfree.com.br', 'britneyclub.com', 'broadwaybuff.com', 
     'broadwaylove.com', 'brokeandhappy.com', 'brujula.net', 'brunetka.ru', 'btcc.org', 'bulgaria.com', 'bunita.net', 
     'burntmail.com', 'bushemail.com', 'businessman.net', 'bust.com', 'butch-femme.net', 'butovo.net', 'buzy.com', 
     'bvimailbox.com', 'byke.com', 'c3.hu', 'c4.com', 'cairomail.com', 'calcuttaads.com', 'callnetuk.com', 
     'canada-11.com', 'canada.com', 'canoemail.com', 'caramail.com', 'care2.com', 'carioca.net', 'cashette.com', 
     'cataloniamail.com', 'cataz.com', 'catcha.com', 'catemail.com', 'catholic.org', 'catlover.com', 'celineclub.com', 
     'centralpets.com', 'centrum.cz', 'centrum.sk', 'chaiyo.com', 'chaiyomail.com', 'chalkmail.net', 'chance2mail.com', 
     'channelonetv.com', 'charityemail.com', 'chat.ru', 'chatlane.ru', 'chattown.com', 'check1check.com', 'cheeb.com', 
     'cheerful.com', 'chefmail.com', 'chemist.com', 'chequemail.com', 'cheshiremail.com', 'chickmail.com', 
     'chil-e.com', 'chinesecool.com', 'chirk.com', 'chocaholic.com.au', 'chocofan.com', 'chronicspender.com', 
     'ciaoweb.it', 'cirquefans.com', 'city-of-swansea.com', 'city-of-westminster.com', 'citynetusa.com', 
     'claramail.com', 'clerk.com', 'clickforadate.com', 'cliffhanger.com', 'close2you.net', 'cluemail.com', 'cmail.ru', 
     'cmpnetmail.com', 'collegeclub.com', 'columnist.com', 'comic.com', 'complxmind.com', 'compuserve.com', 
     'computer-expert.net', 'computerconfused.com', 'computermail.net', 'computernaked.com', 'cong.ru', 
     'connect4free.net', 'connectbox.com', 'consultant.com', 'cookiemonster.com', 'cool.br', 'coolgoose.com', 
     'coolkiwi.com', 'coollist.com', 'coolmail.com', 'coolmail.net', 'coolrio.com', 'coolsend.com', 'copacabana.com', 
     'copticmail.com', 'corrsfan.com', 'cosmo.com', 'counsellor.com', 'craftemail.com', 'crazy.ru', 'crewstart.com', 
     'critterpost.com', 'croeso.com', 'crosswinds.net', 'crunkmail.com', 'cry4helponline.com', 'cryingmail.com', 
     'cs.com', 'cumbriamail.com', 'curio-city.com', 'cutekittens.com', 'cutey.com', 'cww.de', 'cybercity-online.net', 
     'cyberinbox.com', 'cyberleports.com', 'cybernet.it', 'cymail.net', 'dabsol.net', 'dansegulvet.com', 'data54.com', 
     'date.by', 'dbzmail.com', 'dcsi.net', 'deafemail.net', 'dearriba.com', 'deepseafisherman.net', 
     'deforestationsucks.com', 'degoo.com', 'deliveryman.com', 'desertmail.com', 'desertonline.com', 
     'desertsaintsmail.com', 'desilota.com', 'deskpilot.com', 'despammed.com', 'detik.com', 'dezigner.ru', 'di-ve.com', 
     'diamondemail.com', 'didamail.com', 'diehardmail.com', 'digitalforeplay.net', 'digosnet.com', 'diplomats.com', 
     'director-general.com', 'diri.com', 'discoverymail.net', 'disinfo.net', 'divorcedandhappy.com', 'dmailman.com', 
     'dmitrovka.net', 'dmitry.ru', 'dnsmadeeasy.com', 'doar.net', 'doctor.com', 'dodgeit.com', 'doglover.com', 
     'dogmail.co.uk', 'doityourself.com', 'doneasy.com', 'donegal.net', 'donjuan.com', 'dontgotmail.com', 
     'doramail.com', 'dostmail.com', 'dotcom.fr', 'dotnow.com', 'dott.it', 'dplanet.ch', 'dr.com', 'dragoncon.net', 
     'dubaimail.com', 'dublin.com', 'dustdevil.com', 'dvd-fan.net', 'dygo.com', 'dynamitemail.com', 'e-apollo.lv', 
     'e-hkma.com', 'e-mail.ru', 'e-mailanywhere.com', 'e-mails.ru', 'e-tapaal.com', 'e-webtec.com', 'eastmail.com', 
     'eastrolog.com', 'easy.com', 'easypeasy.com', 'ebprofits.net', 'eircom.net', 'elitemail.org', 'elsitio.com', 
     'eltimon.com', 'elvis.com', 'email-london.co.uk', 'email-value.com', 'email.com', 'email.cz', 'email.it', 
     'email.nu', 'email.ro', 'email.ru', 'email.si', 'email2me.com', 'email2me.net', 'emailacc.com', 'emailaccount.com', 
     'emailaddresses.com', 'emailchoice.com', 'emailforyou.net', 'emailgaul.com', 'emailgroups.net', 'emailoregon.com', 
     'emailpinoy.com', 'emailplanet.com', 'emailplus.org', 'emails.ru', 'emailservice.com', 'emailsydney.com', 
     'emailx.net', 'emale.ru', 'ematic.com', 'empereur.com', 'emptymail.com', 'enel.net', 'enelpunto.net', 'engineer.com', 
     'england.com', 'epatra.com', 'epiqmail.com', 'epomail.com', 'epost.de', 'eprompter.com', 'eresmas.com', 'eriga.lv', 
     'eshche.net', 'esmailweb.net', 'etoast.com', 'eudoramail.com', 'europe.com', 'euroseek.com', 'evafan.com', 
     'evertonfans.com', 'everymail.net', 'everyone.net', 'excite.co.jp', 'excite.com', 'execs.com', 'execs2k.com', 
     'executivemail.co.za', 'extended.com', 'ezagenda.com', 'ezcybersearch.com', 'ezmail.ru', 'fadrasha.net', 
     'fadrasha.org', 'fannclub.com', 'fast-mail.org', 'fastemailer.com', 'fastermail.com', 'fastest.cc', 'fastimap.com', 
     'fastmail.fm', 'fastmail.gr', 'fastmessaging.com', 'fatyachts.com', 'female.ru', 'fepg.net', 'ffanet.com', 
     'fiberia.com', 'filipinolinks.com', 'financefan.net', 'financier.com', 'findfo.com', 'findmail.com', 
     'findmemail.com', 'fineemail.com', 'finklfan.com', 'flashmail.com', 'flipcode.com', 'floridaemail.net', 
     'flytecrew.com', 'fmail.co.uk', 'fmgirl.com', 'fmguy.com', 'fnmail.com', 'forfree.at', 'fortuncity.com', 
     'forum.dk', 'fossefans.com', 'francefans.com', 'free.fr', 'freeaccess.nl', 'freefanmail.com', 'freegates.be', 
     'freeler.nl', 'freemail.bozz.com', 'freemail.com.au', 'freemail.com.pk', 'freemail.de', 'freemail.gr', 
     'freemail.hu', 'freemail.it', 'freemail.lt', 'freemail.nl', 'freemail.org.mk', 'freemail.ru', 'freenet.de', 
     'freenet.kg', 'freeola.net', 'freeproblem.com', 'freesbee.fr', 'freeserve.co.uk', 'freestart.hu', 'freesurf.fr', 
     'freesurf.nl', 'freeuk.com', 'freeuk.net', 'freewebemail.com', 'freeyellow.com', 'fresnomail.com', 'friction.net', 
     'friendlydevices.com', 'frominter.net', 'fromru.com', 'fromru.ru', 'front.ru', 'fsmail.net', 'ftml.net', 
     'funiran.com', 'fusemail.com', 'fut.es', 'gamebox.com', 'gamebox.net', 'gardener.com', 'gatwickemail.com', 
     'gawab.com', 'gay.com', 'gazeta.pl', 'gdi.net', 'geeklife.com', 'genxemail.com', 'geologist.com', 'geopia.com', 
     'gfxartist.ru', 'giga4u.de', 'glay.org', 'glendale.net', 'globalsite.com.br', 'globetrotter.net', 'gmail.com', 
     'gmx.net', 'go.com', 'go.ro', 'go.ru', 'go2net.com', 'go4.it', 'gofree.co.uk', 'goldenmail.ru', 'goldmail.ru', 
     'golfemail.com', 'gonuts4free.com', 'goosemoose.com', 'goplay.com', 'gotmail.com', 'gotomy.com', 'graffiti.net', 
     'graphic-designer.com', 'gratisweb.com', 'grungecafe.com', 'guessmail.com', 'guju.net', 'guy.com', 
     'guyanafriends.com', 'gwhsgeckos.com', 'gyorsposta.com', 'hablas.com', 'hailmail.net', 'hairdresser.com', 
     'hairdresser.net', 'handbag.com', 'hangglidemail.com', 'happemail.com', 'happycounsel.com', 'haramamba.ru', 
     'hardyoungbabes.com', 'healthemail.net', 'heavynoize.net', 'heesun.net', 'hellokitty.com', 'heremail.com', 
     'hewgen.ru', 'hideakifan.com', 'highquality.com', 'hinduhome.com', 'hingis.org', 'hispavista.com', 
     'hitmanrecords.com', 'home.no.net', 'home.ro', 'home.se', 'homelocator.com', 'homenetmail.com', 
     'homeonthethrone.com', 'homestead.com', 'hot-shop.com', 'hot-shot.com', 'hot.ee', 'hotbot.com', 'hotbox.ru', 
     'hotcoolmail.com', 'hotfire.net', 'hotlinemail.com', 'hotmail.co.il', 'hotmail.com', 'hotmail.it', 'hotmail.kg', 
     'hotmail.ro', 'hotmail.ru', 'hotpop.com', 'hotpop3.com', 'hotvoice.com', 'housemail.com', 'hsuchi.net', 
     'humanux.com', 'humour.com', 'hushmail.com', 'i-france.com', 'i-love-cats.com', 'i-mail.com.au', 'i-p.com', 
     'i2828.com', 'iam4msu.com', 'iamfinallyonline.com', 'icestorm.com', 'icq.com', 'icqmail.com', 'icrazy.com', 
     'id.ru', 'idirect.com', 'iespana.es', 'ignmail.com', 'ilovegiraffes.net', 'ilovelionking.com', 
     'ilovepokemonmail.com', 'ilovetocollect.net', 'imail.ru', 'imailbox.com', 'imap-mail.com', 'imel.org', 'in-box.net', 
     'iname.com', 'inbox.lv', 'inbox.net', 'inbox.ru', 'incamail.com', 'indexa.fr', 'india.com', 'indus.ru', 
     'infoapex.com', 'infohq.com', 'infomail.es', 'infomart.or.jp', 'infovia.com.ar', 'inicia.es', 'inmail.sk', 
     'inonesearch.com', 'inorbit.com', 'inspectorjavert.com', 'insurer.com', 'interfree.it', 'interia.pl', 
     'interlap.com.ar', 'internet-e-mail.com', 'internetbiz.com', 'internetegypt.com', 'internetmailing.net', 
     'inwind.it', 'iobox.com', 'iobox.fi', 'iol.it', 'iol.pt', 'ip3.com', 'ipex.ru', 'iportalexpress.com', 'iqemail.com', 
     'irangate.net', 'iraqmail.com', 'iscooler.com', 'islandemail.net', 'ismart.net', 'isonfire.com', 'isp9.net', 
     'itmom.com', 'ivillage.com', 'iwan-fals.com', 'iwon.com', 'jabble.com', 'japan.com', 'jaydemail.com', 
     'jeanvaljean.com', 'jesusanswers.com', 'jetemail.net', 'jfkislanders.com', 'jingjo.net', 'jippii.fi', 'joinme.com', 
     'jojomail.com', 'jordanmail.com', 'journalist.com', 'joymail.com', 'jpopmail.com', 'jumpy.it', 'juniormail.com', 
     'juno.com', 'justmail.de', 'justmailz.com', 'justmarriedmail.com', 'k.ro', 'kaazoo.com', 'kabissa.org', 
     'kaduku.net', 'kalpoint.com', 'karachioye.com', 'katamail.com', 'kebi.com', 'keko.com.ar', 'keptprivate.com', 
     'keromail.com', 'kewpee.com', 'kichimail.com', 'killamail.com', 'killergreenmail.com', 'kimo.com', 
     'kinki-kids.com', 'kitemail.com', 'kittymail.com', 'kiwibox.com', 'kiwitown.com', 'km.ru', 'koko.com', 
     'konkovo.net', 'konsul.ru', 'kosino.net', 'kreditor.ru', 'krovatka.net', 'krunis.com', 'kukamail.com', 
     'kuwait-mail.com', 'kuzminki.net', 'kyokodate.com', 'kyokofukada.net', 'ladyfire.com', 'ladymail.cz', 
     'lahoreoye.com', 'lakmail.com', 'land.ru', 'langoo.com', 'lankamail.com', 'laposte.net', 'latinmail.com', 
     'lawyer.com', 'learn2compute.net', 'lebanonatlas.com', 'leehom.net', 'lefortovo.net', 'legislator.com', 
     'legistrator.com', 'lenta.ru', 'leonlai.net', 'levele.com', 'lianozovo.net', 'liberomail.com', 'linkmaster.com', 
     'linuxfreemail.com', 'linuxmail.org', 'lionsfan.com.au', 'lissamail.com', 'list.ru', 'literaturelover.com', 
     'ljiljan.com', 'llandudno.com', 'llangollen.com', 'lobbyist.com', 'localgenius.com', 'lolnetwork.net', 
     'london.com', 'looksmart.co.uk', 'looksmart.com', 'looksmart.com.au', 'lopezclub.com', 'louiskoo.com', 'lov.ru', 
     'loveable.com', 'lovecat.com', 'loveforlostcats.com', 'lovemail.com', 'lovetocook.net', 'lovetohike.com', 
     'lovingjesus.com', 'lubovnik.ru', 'luso.pt', 'luukku.com', 'luvrhino.com', 'lvwebmail.com', 'lycos.co.uk', 
     'lycos.com', 'lycos.it', 'lycos.ne.jp', 'lycos.ru', 'lycosmail.com', 'mac.com', 'macbox.ru', 'machinecandy.com', 
     'macmail.com', 'mad.scientist.com', 'madcrazy.com', 'madrid.com', 'magicmail.co.za', 'mail-box.cz', 
     'mail-center.com', 'mail.az', 'mail.co.za', 'mail.com', 'mail.ee', 'mail.gr', 'mail.md', 'mail.pf', 'mail.pt', 
     'mail.ru', 'mail.vu', 'mail2k.ru', 'mail2world.com', 'mail3000.com', 'mail333.com', 'mail8.com', 'mailandnews.com', 
     'mailasia.com', 'mailblocks.com', 'mailbolt.com', 'mailbox.as', 'mailbox.gr', 'mailbox.hu', 'mailbr.com.br', 
     'mailchoose.co', 'mailcity.com', 'mailclub.fr', 'mailclub.net', 'mailexcite.com', 'mailfly.com', 'mailfreeway.com', 
     'mailgate.ru', 'mailgenie.net', 'mailhood.com', 'mailingweb.com', 'mailisent.com', 'mailite.com', 'mailme.dk', 
     'mailmight.com', 'mailmij.nl', 'mailops.com', 'mailoye.com', 'mailpanda.com', 'mailpride.com', 'mailpuppy.com', 
     'mailroom.com', 'mailru.com', 'mailserver.ru', 'mailsnare.net', 'mailsurf.com', 'mailworks.org', 'maktoob.com', 
     'malayalamtelevision.net', 'malayalapathram.com', 'male.ru', 'manager.de', 'manlymail.net', 'mantrafreenet.com', 
     'mantramail.com', 'mantraonline.com', 'manutdfans.com', 'marchmail.com', 'marfino.net', 'margarita.ru', 
     'marijuana.nl', 'marketingfanatic.com', 'marketweighton.com', 'marriedandlovingit.com', 'marry.ru', 
     'martinguerre.net', 'masrawy.com', 'mauimail.com', 'maximumedge.com', 'maxleft.com', 'mayaple.ru', 'mcrmail.com', 
     'meanpeoplesuck.com', 'meatismurder.net', 'meetingmall.com', 'megago.com', 'megamail.pt', 'melodymail.com', 
     'meloo.com', 'menja.net', 'merseymail.com', 'mesra.net', 'messagez.com', 'metacrawler.com', 'miesto.sk', 
     'milmail.com', 'mindless.com', 'minermail.com', 'minister.com', 'misery.net', 'mixmail.com', 'ml1.net', 
     'mlanime.com', 'mmail.com', 'mo3gov.net', 'mobico.ru', 'modemnet.net', 'modernenglish.com', 'modomail.com', 
     'moldova.com', 'moldovacc.com', 'mom-mail.com', 'monsieurcinema.com', 'montevideo.com.uy', 'moomia.com', 
     'moose-mail.com', 'mosaicfx.com', 'moscowmail.com', 'mosk.ru', 'motorcyclefan.net', 'motormania.com', 
     'movemail.com', 'movieemail.net', 'mozartmail.com', 'mozhno.net', 'mp3haze.com', 'mrspender.com', 'msgbox.com', 
     'msx.ru', 'mundomail.net', 'munich.com', 'music.maigate.ru', 'musician.com', 'musician.org', 'mycabin.com', 
     'mycool.com', 'mydomain.com', 'myfunnymail.com', 'myiris.com', 'myjazzmail.com', 'mymac.ru', 'mymail.ro', 
     'mynamedot.com', 'myotw.net', 'mypersonalemail.com', 'myplace.com', 'myrealbox.com', 'myself.com', 'myway.com', 
     'myworldmail.com', 'n2.com', 'n2business.com', 'n2mail.com', 'n2software.com', 'nagarealm.com', 'name.com', 
     'nameplanet.com', 'nanaseaikawa.com', 'nandomail.com', 'naseej.com', 'nativestar.net', 'nativeweb.net', 'nc.ru', 
     'nekto.com', 'nekto.net', 'nekto.ru', 'nemra1.com', 'nenter.com', 'nervhq.org', 'net4b.pt', 'net4you.at', 
     'netaddres.ru', 'netaddress.ru', 'netbounce.com', 'netbroadcaster.com', 'netcity.ru', 'netcourrier.com', 
     'netfirms.com', 'netizen.com.ar', 'netkushi.com', 'netmail.kg', 'netman.ru', 'netmongol.com', 'netpiper.com', 
     'netposta.net', 'netscape.net', 'netscapeonline.co.uk', 'netsquare.com', 'nettaxi.com', 'netzero.com', 
     'netzoola.com', 'neustreet.com', 'newap.ru', 'newarbat.net', 'newmail.com', 'newmail.net', 'newmail.ru', 
     'newyork.com', 'newyorkcity.com', 'nfmail.com', 'ngs.ru', 'nicegal.com', 'nicholastse.net', 'nicolastse.com', 
     'nightimeuk.com', 'nightmail.com', 'nightmail.ru', 'nikulino.net', 'nm.ru', 'nnov.ru', 'no4ma.ru', 'noavar.com', 
     'nonstopcinema.com', 'norikomail.com', 'nospammail.net', 'notyouagain.com', 'novogireevo.net', 'novokosino.net', 
     'numep.ru', 'nuvse.com', 'ny.com', 'nybce.com', 'nyc.com', 'nycmail.com', 'nz11.com', 'nzoomail.com', 'o2.pl', 
     'oceanfree.net', 'ochakovo.net', 'oddpost.com', 'odmail.com', 'oicexchange.com', 'ok.kz', 'ok.ru', 
     'oldbuthealthy.com', 'ole.com', 'olemail.com', 'oligarh.ru', 'olympist.net', 'omaninfo.com', 'omen.ru', 
     'ondikoi.com', 'onebox.com', 'onenet.com.ar', 'onet.pl', 'oninet.pt', 'online.ie', 'online.ru', 
     'onlinecasinogamblings.com', 'onlinewiz.com', 'onobox.com', 'opendiary.com', 'operamail.com', 'optician.com', 
     'orbitel.bg', 'orgmail.net', 'osite.com.br', 'oso.com', 'otakumail.com', 'ournet.md', 'outgun.com', 'ozz.ru', 
     'paidforsurf.com', 'pakistanoye.com', 'palestinemail.com', 'pandawa.com', 'pandora.be', 'paradiseemail.com', 
     'paris.com', 'pathfindermail.com', 'patmail.com', 'patra.net', 'pechkin.ru', 'pediatrician.com', 'pekklemail.com', 
     'penpen.com', 'peopleweb.com', 'perfectmail.com', 'perovo.net', 'personal.ro', 'personales.com', 'petr.ru', 
     'phreaker.net', 'piercedallover.com', 'pigeonportal.com', 'pigmail.net', 'pigpig.net', 'pilotemail.com', 
     'pimagop.com', 'pinoymail.com', 'pisem.net', 'planetaccess.com', 'planetout.com', 'plasa.com', 'playersodds.com', 
     'playful.com', 'pluno.com', 'plusmail.com.br', 'pmail.net', 'pobox.ru', 'pobox.sk', 'pochta.by', 'pochta.ws', 
     'pochtamt.ru', 'poczta.fm', 'poetic.com', 'polbox.com', 'poohfan.com', 'pop3.ru', 'popaccount.com', 'popmail.com', 
     'popsmail.com', 'popstar.com', 'portugalmail.com', 'portugalnet.com', 'post.com', 'post.cz', 'post.sk', 
     'postino.ch', 'postino.it', 'postmaster.co.uk', 'powerdivas.com', 'powerfan.com', 'praize.com', 
     'predprinimatel.ru', 'premiumproducts.com', 'premiumservice.com', 'prepodavatel.ru', 'presidency.com', 
     'presnya.net', 'press.co.jp', 'prettierthanher.com', 'priest.com', 'primposta.com', 'printesamargareta.ro', 
     'professor.ru', 'programist.ru', 'programmer.net', 'prokuratura.ru', 'promessage.com', 'prontomail.com', 
     'publicist.com', 'punkass.com', 'puppy.com.my', 'purinmail.com', 'qatarmail.com', 'qdice.com', 'qrio.com', 
     'quake.ru', 'qudsmail.com', 'quepasa.com', 'quickmail.ru', 'quickwebmail.com', 'r-o-o-t.com', 'raakim.com', 
     'racingfan.com.au', 'radicalz.com', 'ragingbull.com', 'rambler.ru', 'ranmamail.com', 'ravearena.com', 
     'ravefan.com', 'ravemail.co.za', 'razormail.com', 'realestatemail.net', 'realtyagent.com', 'recycledmail.com', 
     'rediffmail.com', 'rediffmailpro.com', 'redseven.de', 'redwhitearmy.com', 'registerednurses.com', 'relia.com', 
     'repairman.com', 'represantive.com', 'representative.com', 'rescueteam.com', 'retailfan.com', 'rexian.com', 
     'rickymail.com', 'ring.by', 'rn.com', 'roanokemail.com', 'rock.com', 'rocketmail.com', 'rojname.com', 'rol.ro', 
     'rome.com', 'romymichele.com', 'rpharmacist.com', 'rt.nl', 'ru.ru', 'runbox.com', 'rushpost.com', 's-mail.com', 
     'sacbeemail.com', 'safe-mail.net', 'sailormoon.com', 'saint-mike.org', 'saintly.com', 'samerica.com', 
     'samilan.net', 'samiznaetekogo.net', 'sammimail.com', 'sanchezsharks.com', 'sanfranmail.com', 'sanriotown.com', 
     'santanmail.com', 'saturnfans.com', 'saturnperformance.com', 'saudia.com', 'savecougars.com', 'saveowls.com', 
     'sayhi.net', 'scfn.net', 'schweiz.org', 'sci.fi', 'scientist.com', 'scottishmail.co.uk', 'scottishtories.com', 
     'scrapbookscrapbook.com', 'search417.com', 'sebil.com', 'seckinmail.com', 'secretservices.net', 'seductive.com', 
     'sekomaonline.com', 'sellingspree.com', 'sendmail.ru', 'sendme.cz', 'serga.com.ar', 'servemymail.com', 
     'sesmail.com', 'sexmagnet.com', 'seznam.cz', 'shaniastuff.com', 'shellov.net', 'shootmail.com', 'showfans.com', 
     'shuf.com', 'sify.com', 'sigaret.net', 'simbamail.fm', 'sinamail.com', 'singapore.com', 'singmail.com', 
     'singnet.com.sg', 'sirindia.com', 'skim.com', 'skunkbox.com', 'slamdunkfan.com', 'slickriffs.co.uk', 
     'slingshot.com', 'slo.net', 'smapxsmap.net', 'sminkymail.com', 'smtp.ru', 'snail-mail.net', 'sndt.net', 
     'sneakemail.com', 'snoopymail.com', 'snowboarding.com', 'so-simple.org', 'socamail.com', 'socceraccess.com', 
     'sociologist.com', 'softhome.net', 'sokolniki.net', 'sol.dk', 'soon.com', 'soulfoodcookbook.com', 
     'soundofmusicfans.com', 'southparkmail.com', 'sovsem.net', 'sp.nl', 'space.com', 'spacetowns.com', 'spamex.com', 
     'spankthedonkey.com', 'spartapiet.com', 'spazmail.com', 'spils.com', 'spinfinder.com', 'spiritseekers.com', 
     'sportemail.com', 'sportmail.ru', 'spray.no', 'spray.se', 'srilankan.net', 'stade.fr', 'stalag13.com', 
     'standalone.net', 'starbuzz.com', 'starmail.org', 'starmedia.com', 'starspath.com', 'start.com.au', 
     'starwars-fans.com', 'stillchronic.com', 'stockstorm.com', 'stribmail.com', 'sudanmail.net', 'sueddeutsche.de', 
     'suisse.org', 'sunmail1.com', 'sunpoint.net', 'supermail.ru', 'superman.ru', 'surf3.net', 'surfsupnet.net', 
     'surfy.net', 'surimail.com', 'survivormail.com', 'sviblovo.net', 'sweb.cz', 'swiftdesk.com', 'swirve.com', 
     'swissinfo.org', 'swissmail.net', 'switchboardmail.com', 'switzerland.org', 'syriamail.com', 't2mail.com', 
     'table of free mail providers used in spam', 'takoe.com', 'takoe.net', 'talk21.com', 'talkcity.com', 'tamb.ru', 
     'tangmonkey.com', 'taotaotano.com', 'tatanova.com', 'tattooedallover.com', 'tattoofanatic.com', 'teacher.com', 
     'techemail.com', 'techie.com', 'technologist.com', 'technologyandstocks.com', 'techsniper.com', 'telebot.com', 
     'teleline.es', 'telinco.net', 'telpage.net', 'tenchiclub.com', 'terra.cl', 'terra.com', 'terra.com.ar', 
     'terra.com.br', 'terra.es', 'tfz.net', 'tgasa.ru', 'tgma.ru', 'tgngu.ru', 'tgu.ru', 'thai.com', 'thaimail.com', 
     'thaimail.net', 'the-fastest.net', 'the-professional.com', 'the-quickest.com', 'the-seasiders.com', 
     'the-wild-west.com', 'thedoghousemail.com', 'theheadoffice.com', 'theinternetemail.com', 'theoffice.net', 
     'thepostmaster.net', 'theracetrack.com', 'thereisnogod.com', 'thesimpsonsfans.com', 'thewatercooler.com', 
     'thewebpros.co.uk', 'thirdage.com', 'thundermail.com', 'tibetemail.com', 'timormail.com', 'tipsandadvice.com', 
     'tiran.ru', 'tiscali.co.uk', 'tiscali.it', 'tiscali.se', 'tkcity.com', 'tlcfan.com', 'tmicha.net', 'tokyo.com', 
     'topchat.com', 'topmail.com.ar', 'topsurf.com', 'toquedequeda.com', 'torba.com', 'torchmail.com', 'totalmail.com', 
     'totalsurf.com', 'toughguy.net', 'trainspottingfan.com', 'trevas.net', 'trjam.net', 'truckeremail.net', 
     'tulipsmail.net', 'tunisiamail.com', 'turkey.com', 'tushino.net', 'tut.by', 'tverskie.net', 'tverskoe.net', 
     'tvnet.lv', 'twentylove.com', 'twinstarsmail.com', 'tycoonmail.com', 'typemail.com', 'tyt.by', 'u2club.com', 
     'ua.fm', 'uae.ac', 'uaemail.com', 'ubbi.com', 'uboot.com', 'uk2.net', 'uk2net.com', 'ukr.net', 'ukrpost.net', 
     'ukrtop.com', 'ultimatelimos.com', 'ultrapostman.com', 'umpire.com', 'unbounded.com', 'underwriters.com', 
     'uni.de', 'unican.es', 'uogtritons.com', 'uol.com.ar', 'uol.com.br', 'uol.com.co', 'uol.com.mx', 'uol.com.ve', 
     'uole.com', 'uole.com.ve', 'uolmail.com', 'uomail.com', 'uraniomail.com', 'ureach.com', 'usa.com', 
     'usanetmail.com', 'userbeam.com', 'userzap.com', 'uymail.com', 'uyuyuy.com', 'uzhe.net', 'v-sexi.com', 
     'v8email.com', 'valudeal.net', 'velnet.com', 'verizonmail.com', 'verticalheaven.com', 'vip.gr', 'vipmail.ru', 
     'virgilio.it', 'virgin.net', 'virtual-mail.com', 'virtualguam.com', 'virtualmail.com', 'visitmail.com', 
     'visto.com', 'viwanet.ru', 'vjtimail.com', 'vlcity.ru', 'vnn.vn', 'vnukovo.net', 'voila.fr', 'volcanomail.com', 
     'vovan.ru', 'vyhino.net', 'wahoye.com', 'wales2000.net', 'wam.co.za', 'wanaboo.com', 'wapda.com', 'warmmail.com', 
     'watchmail.com', 'waumail.com', 'wearab.net', 'web-mail.com.ar', 'web.de', 'webaddressbook.com', 'webbworks.com', 
     'webcity.ca', 'webdream.com', 'webemaillist.com', 'webindia123.com', 'webjump.com', 'webmail.co.yu', 
     'webmail.co.za', 'webmail.ru', 'webmails.com', 'webmailv.com', 'webskulker.com', 'webstation.com', 
     'websurfer.co.za', 'webtopmail.com', 'webtribe.net', 'weedmail.com', 'weekonline.com', 'wesleymail.com', 
     'whale-mail.com', 'wheelweb.com', 'whipmail.com', 'whoever.com', 'wholefitness.com', 'wildmail.com', 
     'winmail.com.au', 'winning.com', 'winrz.com', 'witty.com', 'wombles.com', 'women-only.net', 'wongfaye.com', 
     'wooow.it', 'work4teens.com', 'workmail.co.za', 'workmail.com', 'worldbreak.com', 'worldemail.com', 
     'wowmail.com', 'wp.pl', 'writeme.com', 'writemeback.com', 'writeremail.com', 'wrongmail.com', 'www.com', 
     'wxs.net', 'x-mail.net', 'xaker.ru', 'xmenfans.com', 'xmsg.com', 'xoom.com', 'xpectmore.com', 'xsmail.com', 
     'xtram.com', 'xzapmail.com', 'yaho.com', 'yahoo.co.jp', 'yahoo.co.kr', 'yahoo.co.nz', 'yahoo.co.uk', 'yahoo.com', 
     'yahoo.com.ar', 'yahoo.com.au', 'yahoo.com.br', 'yahoo.com.co', 'yahoo.com.hk', 'yahoo.com.is', 'yahoo.com.mx', 
     'yahoo.com.ru', 'yahoo.com.sg', 'yahoo.de', 'yahoo.dk', 'yahoo.es', 'yahoo.fr', 'yahoo.ie', 'yahoo.it', 
     'yahoo.jp', 'yahoo.ru', 'yahoo.se', 'yahoofs.com', 'yahoomail.com', 'yam.com', 'yandex.ru', 'yeehaa.com', 
     'yehey.com', 'yemenmail.com', 'yepmail.net', 'yeswebmaster.com', 'yifan.net', 'yourinbox.com', 'yours.com', 
     'yourwap.com', 'youthfire.com', 'youthpost.com', 'yuuhuu.net', 'yyhmail.com', 'z6.com', 'zdorovja.net', 
     'zensearch.com', 'zip.net', 'zipido.com', 'ziplip.com', 'zipmail.com', 'zipmail.com.br', 'zipmax.com', 'zmail.pt', 
     'zmail.ru', 'zonai.com', 'zoneview.net', 'zonnet.nl', 'zubee.com', 'zvmail.com', 'zwallet.com', 'zybermail.com',
     'globo.com'
               
    ]